StudentsSurveySystem/StudentsSurveySystem/Controllers/SurveysController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StudentsSurveySystem.Models;

namespace StudentsSurveySystem.Controllers
{
    public class SurveysController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //Get: Survey by category
        public ActionResult Category1()
        {
            var surveys = db.Surveys.Include(s => s.Category).Where(c => c.CategoryID == 1);
            return View(surveys.ToList());
        }

        public ActionResult Category2()
        {
            var surveys = db.Surveys.Include(s => s.Category).Where(c => c.CategoryID == 2);
            return View(surveys.ToList());
        }

        public ActionResult Category3()
        {
            var surveys = db.Surveys.Include(s => s.Category).Where(c => c.CategoryID == 3);
            return View(surveys.ToList());
        }
        //-----------------------

        // GET: Surveys
        public ActionResult Index()
        {
            var surveys = db.Surveys.Include(s => s.Category);
            return View(surveys.ToList());
        }

        // GET: Surveys/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            return View(survey);
        }

        // GET: Surveys/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            return View();
        }

        // POST: Surveys/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,CategoryID")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                db.Surveys.Add(survey);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", survey.CategoryID);
            return View(survey);
        }

        // GET: Surveys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", survey.CategoryID);
            return View(survey);
        }

        // POST: Surveys/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,CategoryID")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                db.Entry(survey).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", survey.CategoryID);
            return View(survey);
        }

        // GET: Surveys/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            return View(survey);
        }

        // POST: Surveys/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Survey survey = db.Surveys.Find(id);
            db.Surveys.Remove(survey);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StudentsSurveySystem/StudentsSurveySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <style>
    
    .dropdown-menu {
        opacity: 0.9 !important;
     }
    </style>
    @section Scripts
    { }
    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Добре дошли!", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(" Home", "Index", "Home", new { area = "" }, new { @class = "glyphicon glyphicon-home" })</li>   
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle glyphicon glyphicon-th-list" data-toggle="dropdown" role="button"
                           aria-expanded="false"> Анкети<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu" id="myTab">
                            <li role="presentation">
                                <a href="" aria-controls="" role="tab" data-toggle="tab">
                                    @Html.ActionLink("Оценка на студентите за условията за научно изследователска дейност", "Category1", "Surveys")
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="" aria-controls="" role="tab" data-toggle="tab">
                                    @Html.ActionLink("Оценка на качеството на учебния процес", "Category2", "Surveys")
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li role="presentation">
                                <a href="" aria-controls="" role="tab" data-toggle="tab">
                                    @Html.ActionLink("Оценка за престижа на университета сред студентите", "Category3", "Surveys")
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink(" За нас", "About", "Home", new { area = "" }, new { @class = "glyphicon glyphicon-info-sign" })</li>
                    <li>@Html.ActionLink(" Контакти", "Contact", "Home", new { area = "" }, new { @class = "glyphicon glyphicon-envelope" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>

        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            @*<footer>
                <p>&copy; @DateTime.Now.Year - Студентска система за анкетиране</p>
            </footer>*@
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function () {
            $(window).on('scroll', function (e) {
                if ($(document).scrollTop() === 0) {
                    $('.navbar').css('opacity', 1);
                }
                else {
                    $('.navbar').css('opacity', (1 - $(document).scrollTop() / 500));
                }
            });
        });
    </script>
</body>
</html>